### ISSUE TITLE
自定义函数调用不支持三个以上的参数吗？ 

### ISSUE THREAD

**Issue by hongminzheng** [nwkl-home/valuate#1]
请问大佬，自定义函数调用不支持三个以上的参数吗？

**Comment by hongminzheng** [comment]
![image](https://github.com/nwkl-home/valuate/assets/49329068/dfc08fbf-0d06-4140-9e03-49476b728f44)
EvaluationOperator.java中的第209行
objects = Arrays.asList((Object[]) leftStage);需改成objects.addAll(Arrays.asList((Object[]) leftStage));
否则219行会报错

**Comment by nwkl-home** [comment]
~.~，已经提交了

**Comment by nwkl-home** [comment]
已经提交了，最近都不怎么管~。~
